### ISSUE TITLE
Error while pushing service request to Fulfillment

### ISSUE THREAD

**Issue by shbz1690** [sparc-request/sparc-request#1188]
I have deployed sparc_3.0.0b and when I try to push my request to fulfillment I get the below error in my delayed_jobs table:

`| RemoteServiceNotifierJob::RemoteServiceNotifierError
/opt/SPARC/sparc-request-cnmc/releases/20171108223237/app/jobs/remote_service_notifier_job.rb:35:in `block in perform'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:807:in `process_result'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:725:in `block in transmit'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/net/http.rb:877:in `start'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:715:in `transmit'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:145:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient/request.rb:52:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rest-client-2.0.2/lib/restclient.rb:71:in `post'
/opt/SPARC/sparc-request-cnmc/releases/20171108223237/app/jobs/remote_service_notifier_job.rb:33:in `perform'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:81:in `block in invoke_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/backend/base.rb:78:in `invoke_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:129:in `block in invoke_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:368:in `perform_action_with_newrelic_trace'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/newrelic_rpm-4.5.0.337/lib/new_relic/agent/instrumentation/delayed_job_instrumentation.rb:128:in `invoke_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block (2 levels) in run'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/timeout.rb:93:in `block in timeout'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/timeout.rb:103:in `timeout'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:230:in `block in run'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:229:in `run'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `block in reserve_and_run_one_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:312:in `reserve_and_run_one_job'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:213:in `block in work_off'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `times'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:212:in `work_off'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:175:in `block (4 levels) in start'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:174:in `block (3 levels) in start'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:173:in `block (2 levels) in start'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `loop'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:172:in `block in start'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/plugins/clear_locks.rb:7:in `block (2 levels) in <class:ClearLocks>'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block (2 levels) in add'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:61:in `block in initialize'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:79:in `block in add'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:66:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/lifecycle.rb:40:in `run_callbacks'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/worker.rb:171:in `start'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/delayed_job-4.1.3/lib/delayed/tasks.rb:14:in `block (2 levels) in <top (required)>'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `block in execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `each'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:251:in `execute'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/task.rb:181:in `invoke'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:160:in `invoke_task'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `each'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:116:in `block in top_level'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:125:in `run_with_threads'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:110:in `top_level'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:83:in `block in run'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/lib/rake/application.rb:80:in `run'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/gems/rake-12.2.1/exe/rake:27:in `<top (required)>'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/bin/rake:23:in `load'
/opt/SPARC/sparc-request-cnmc/shared/bundle/ruby/2.4.0/bin/rake:23:in `<top (required)>'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `load'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:75:in `kernel_load'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli/exec.rb:28:in `run'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:424:in `exec'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:27:in `dispatch'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/cli.rb:18:in `start'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:30:in `block in <top (required)>'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/lib/bundler/friendly_errors.rb:122:in `with_friendly_errors'
/home/capistrano/.rbenv/versions/2.4.2/lib/ruby/gems/2.4.0/gems/bundler-1.16.0/exe/bundle:22:in `<top (required)>'
/home/capistrano/.rbenv/versions/2.4.2/bin/bundle:23:in `load'
/home/capistrano/.rbenv/versions/2.4.2/bin/bundle:23:in `<main>' |`

I checked my ruby version and it looks like sparc is using correct version:
mskhan2@machinename:/opt/SPARC/sparc-request-cnmc$ rbenv versions
  system
  2.1.5
  2.4.1
* 2.4.2 (set by /opt/SPARC/sparc-request-cnmc/.ruby-version)

capistrano@machinename:/opt/SPARC/sparc-request-cnmc$ rbenv versions
  system
  2.1.5
  2.2.2
  2.4.1
* 2.4.2 (set by /opt/SPARC/sparc-request-cnmc/.ruby-version)

**Comment by WenjunHe1027** [comment]
Sounds like Request can't talk to Fulfillment.  Check the database 'settings' table and see what your remote_service settings are.  I believe there should be 4 settings.

**Comment by wsams** [comment]
Hi @WenjunHe1027 , I know this is an old issue, but maybe the setup is similar in SPARCRequest 3.5.0 and SPARCFulfillment 2.9.0.

I have been setting those `remote_service_notifier_*` values in `sparc-request/config/application.yml`, but not sure if that's correct. They're not set in the database - just the empty defaults. Do the database values override `application.yml`?

I'm also unclear how to generate the username and password, or do we just choose something arbitrary and stick in the db? The docs are also a bit unclear on the host. Is it the fulfillment host?

The `README.md` document in sparc-fulfillment helps a little, but is missing details.

**Comment by wsams** [comment]
I configured the `remote_service_notifier_*` properties in the settings table and updated the env vars `SPARC_API_*` in SPARCFulfillment.

When I go to "Admin Edit" to push to fulfillment, the push button is already a spinner, and Chrome dev tools shows a network request repeating continuously with no end in sight. (Note, I can only find this button in a couple protocols - maybe related to #1945)

![Screen Shot 2019-07-29 at 3 21 47 PM](https://user-images.githubusercontent.com/273863/62086977-f4f07480-b214-11e9-95c7-8627e441f04c.png)

When I look at the network tab > response tab, it shows the following HTML. I'm not clear if that's dev tools choking or sparc. Last week before I made these changes, the "Push to Fulfillment" button was available, but upon pressing it also went into this loop. Not sure why it goes straight to the spinner now.

```
<h4 class='text-center' id='modal-title'>
Internet Explorer Version Warning
</h4>
</div>
<div class='modal-body'>
<div class='form-group'>
<p>
Your browser version is out of date. SPARCRequest does not support Internet Explorer versions older than version 8.
</p>
</div>
<div class='form-group'>
<p>
Using versions lower than 8 can cause data curruption and other serious problems using this tool.
</p>
</div>
</div>
<div class='modal-footer'>
<div class='center-block'></div>
</div>
</div>
</div>
</div>
```
